name: 部署到 Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'
      - '.github/workflows/cf.yml'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出主仓库代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: 安装依赖
        run: pnpm install

      - name: 更新主题包
        run: pnpm update @project-trans/vitepress-theme-project-trans@prerelease

      - name: 构建项目
        run: pnpm build

      - name: 检出 andai-tales
        uses: actions/checkout@v3
        with:
          repository: trans-archive/andai-tales
          path: andai-tales

      - name: 构建 andai-tales
        run: |
          cd andai-tales
          pnpm install
          pnpm update @project-trans/vitepress-theme-project-trans@prerelease
          pnpm build

      - name: 将 andai-tales 移入主站
        run: |
          mkdir -p docs/.vitepress/dist/andai-tales
          cp -r andai-tales/docs/.vitepress/dist/* docs/.vitepress/dist/andai-tales

      - name: 安装 Wrangler
        run: pnpm add -g wrangler@3

      - name: 发布到 Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_PAGES_ACCOUNT }}
          projectName: trans-archive
          directory: docs/.vitepress/dist
